stages:
  - build
  - test
  - publish
  - deploy

variables:
  DOCKER_IMAGE: "lab10ex5/flask-app"
  DOCKER_TAG: "latest"

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  artifacts:
    paths:
      - ./

test:
  stage: test
  script:
    - docker run $DOCKER_IMAGE:$DOCKER_TAG python -m unittest test_app.py

publish:
  stage: publish
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - ssh user@server "docker pull $DOCKER_IMAGE:$DOCKER_TAG && docker run -d -p 5000:5000 $DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main
